version: '3.3'
services:
  mariadb:
    build: ./docker/mariadb
    environment:
      - MYSQL_DATABASE=${SYSTEM_DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - ../mysql_data:/var/lib/mysql
    ports:
      - '3306:3306'
    restart: unless-stopped
  mongo:
    build: ./docker/mongo
    volumes:
      - ../mongodb_data/:/var/lib/mongodb
    ports:
      - '27017:27017'
    restart: unless-stopped
  redis:
    build: ./docker/redis
    volumes:
      - ../redis_data:/data
    expose:
      - "6379"
    restart: unless-stopped
  gotenberg:
    image: thecodingmachine/gotenberg:6
    ports:
      - "9000:3000"
    restart: unless-stopped
  phpmyadmin:
    build: ./docker/phpMyAdmin
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    restart: unless-stopped
  mongo-express:
    image: mongo-express:latest
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=pass
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    restart: unless-stopped
